# Project information
site_name: Paolo
site_url: https://stevemar.github.io/minimal-workshop-mkdocs
site_author: Paolo

# Repository
repo_name: minimal-workshop-mkdocs
repo_url: https://github.com/stevemar/minimal-workshop-mkdocs
# Change the middle parameter to the default branch, "master" or "main"
edit_uri: edit/master/docs

# Navigation
nav:
  - Home: index.md
  - Getting started:
    - Installation: getting-started.md
  - Setup:
    - Changing the colors: setup/changing-the-colors.md

# Theme
theme:
  name: null
  custom_dir: 'wor/'
  icon:
    logo: material/library
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  language: en
  palette:
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde